// priority: 0

console.info('Hello, World! (You will only see this line once in console, during startup)')

const $EventBuses = java('me.shedaniel.architectury.platform.forge.EventBuses')
const $GasDeferredRegister = java('mekanism.common.registration.impl.GasDeferredRegister')

const GASES = new $GasDeferredRegister('kubejs')

onEvent('item.registry', event => {

	event.create('render_eye').displayName('Eye of Render')
	event.create('vanadinite_cluster').displayName('Vanadinite Cluster')
	event.create('tungsten_cluster').displayName('Tungsten Cluster')
	event.create('empty_pcb_stack').displayName('Empty PCB Stack')
	event.create('tool_handle').displayName('Tool Handle')
	event.create('acidic_titanium_salt').displayName('Acidic Titanium Salt')
	event.create('active_infusion_token').displayName('Active Infusion Token')
	event.create('advanced_control_circuit_materials').displayName('Advanced Control Circuit Materials')
	event.create('advanced_crystal_excavation_unit_access_card').displayName('Advanced Crystal Excavation Unit Access Card')
	event.create('advanced_crystal_excavation_unit').displayName('Advanced Crystal Excavation Unit')
	event.create('advanced_thruster').displayName('Advanced Thruster')
	event.create('advanced_plating').displayName('Advanced Plating')
	event.create('advanced_rocket').displayName('Advanced Rocket')
	event.create('aestanite_ingot').displayName('Aestanite Ingot')
	event.create('air_pumping_unit_access_card').displayName('Air Pumping Unit Access Card')
	event.create('air_pumping_unit').displayName('Air Pumping Unit')
	event.create('alumina').displayName('Alumina')
	event.create('aluminum_hydroxide_chunks').displayName('Aluminum Hydroxide Chunks')
	event.create('aluminum_hydroxide_crystal').displayName('Aluminum Hydroxide Crystal')
	event.create('aluminum_hydroxide_shard').displayName('Aluminum Hydroxide Shard')
	event.create('aluminum_iodide').displayName('Aluminum Iodide')
	event.create('ammonium_nitrate').displayName('Ammonium Nitrate')
	event.create('annealed_copper_ingot').displayName('Annealed Copper Ingot')
	event.create('antimatter_singularity').displayName('Antimatter Singularity')
	event.create('antimony_dust').displayName('Antimony Dust')
	event.create('antimony_ingot').displayName('Antimony Ingot')
	event.create('antimony_oxide').displayName('Antimony Oxide')
	event.create('antimony_trichloride').displayName('Antimony Trichloride')
	event.create('asgardian_crystal').displayName('Asgardian Crystal')
	event.create('asteroid_belt_teleportation_device').displayName('Asteroid Belt Teleportation Device')
	event.create('asteroid_collection_unit_access_card').displayName('Asteroid Collection Unit Access Card')
	event.create('asteroid_collection_unit').displayName('Asteroid Collection Unit')
	event.create('azure_substance').displayName('Azure Substance').food(food => {
		food.effect('occultism:third_eye', 260, 1, 1).alwaysEdible()
	})
	event.create('baroness_orb').displayName('Baroness Orb')
	event.create('basic_crystal_excavation_unit_access_card').displayName('Basic Crystal Excavation Unit Access Card')
	event.create('basic_crystal_excavation_unit').displayName('Basic Crystal Excavation Unit')
	event.create('basic_thruster').displayName('Basic Thruster')
	event.create('basic_plating').displayName('Basic Plating')
	event.create('basic_rocket').displayName('Basic Rocket')
	event.create('basic_thruster').displayName('Basic Thruster')
	event.create('bauxite_dust').displayName('Bauxite Dust')
	event.create('blue_plate').displayName('Blue Plate')
	event.create('blue_substance').displayName('Blue Substance')
	event.create('bolt_processing').displayName("Incomplete Bolt")
	event.create('calx_of_the_nether').displayName('Calx of the Nether')
	event.create('certificate_of_crude_steel').displayName('Certificate of Crude Steel')
	event.create('certificate_of_stellar_alloy').displayName('Certificate of Stellar Alloy')
	event.create('certificate_package').displayName('Certificate Package')
	event.create('chromite_dust').displayName('Chromite Dust')
	event.create('chromium_dust').displayName('Chromium Dust')
	event.create('chromiumiii_oxide').displayName('Chromium(III) Oxide')
	event.create('clown_nose').displayName('Clown Nose')
	event.create('coated_aquamarine').displayName('Coated Aquamarine')
	event.create('coated_fiberglass_wool').displayName('Coated Fiberglass Wool')
	event.create('compact_teleportation_core').displayName('Compact Teleportation Core')
	event.create('compressed_advanced_control_circuit_materials').displayName('Compressed Advanced Control Circuit Materials')
	event.create('compressed_elite_control_circuit_materials').displayName('Compressed Elite Control Circuit Materials')
	event.create('compressed_steel_casing_materials').displayName('Compressed Steel Casing Materials')
	event.create('compressed_ultimate_control_circuit_materials').displayName('Compressed Ultimate Control Circuit Materials')
	event.create('concrete_bottle').displayName("Liquid Concrete Bottle").food(food => {
		food.hunger(10).saturation(10).eaten(e => {
			e.server.runCommandSilent(`give ${e.player} minecraft:glass_bottle`);
			e.server.runCommandSilent(`effect give ${e.player} futurepack:paralyze 60 0 true`)
		})
	})
	event.create('conjureditem').displayName('Conjured Dummy Item').tag('kubejs:conjured')
	event.create('corrosive_heart').displayName('Corrosive Heart')
	event.create('corundum_grit').displayName('Corundum Grit')
	event.create('creep_cannon').displayName('C.R.E.E.P. Cannon')
	event.create('crude_titanium_dust').displayName('Crude Titanium Dust')
	event.create('crushed_aestanite').displayName('Crushed Aestanite')
	event.create('crushing_wheel_processing').displayName("Incomplete Crushing Wheel")
	event.create('cryolite_crystal').displayName('Cryolite Crystal')
	event.create('crystocore_essence').displayName('Crystocore Essence')
	event.create('cyanide').displayName('Cyanide')
	event.create('dark_matter_alloy').displayName('Dark Matter Alloy')
	event.create('deep_essence').displayName('Deep Essence')
	event.create('dh3_doped_wafer').displayName('D-H-3 Doped Wafer').glow(true)
	event.create('dimensional_blank_rune').displayName('Dimensional Blank Rune')
	event.create('dimensionally_transcendent_pebble').displayName('Dimensionally Transcendent Pebble')
	event.create('dimensionally_transcendent_pebble_and_hellsteel').displayName('Dimensionally Transcendent Pebble and Hellsteel')
	event.create('dioxygen_difluoride').displayName('Dioxygen Difluoride')
	event.create('dracyon_emitter').displayName('Dracyon Emitter')
	event.create('earthen_essence').displayName('Earthen Essence')
	event.create('elemental_blank_rune').displayName('Elemental Blank Rune')
	event.create('elemental_dust').displayName('Elemental Dust')
	event.create('elite_control_circuit_materials').displayName('Elite Control Circuit Materials')
	event.create('elite_crystal_excavation_unit_access_card').displayName('Elite Crystal Excavation Unit Access Card')
	event.create('elite_crystal_excavation_unit').displayName('Elite Crystal Excavation Unit')
	event.create('empowered_coral').displayName('Empowered Coral')
	event.create('empty_bone').displayName('Empty Bone')
	event.create('enchanted_crystal').displayName('Enchanted Crystal')
	event.create('enriched_uranium_dust').displayName('Enriched Uranium Dust')
	event.create('ender_cube').displayName('Ender Cube')
	event.create('ender_rosin').displayName('Ender Rosin')
	event.create('ender_substrate').displayName('Ender Substrate')
	event.create('enderium_base_ingot').displayName('Enderium Base Ingot')
	event.create('enderium_glass_fragment').displayName('Enderium Glass Fragment')
	event.create('energized_ingot').displayName('Energized Ingot')
	event.create('fading_light_essence').displayName('Fading Light Essence')
	event.create('fiberglass_wool').displayName('Fiberglass Wool')
	event.create('flaming_essence').displayName('Flaming Essence')
	event.create('flex_mesh_processing').displayName("Incomplete Flex Mesh")
	event.create('forged_shard').displayName('Forged Shard')
	event.create('forged_wall_processing').displayName('Incomplete Forged Wall')
	event.create('fossilized_coral').displayName('Fossilized Coral')
	event.create('fragmented_anima_stone').displayName('Fragmented Anima Stone')
	event.create('gaia_infused_integral_components').displayName('Gaia-Infused Integral Components')
	event.create('galvanized_steel_ingot').displayName('Galvanized Steel Ingot')
	event.create('germinated_ebony_seed').displayName('Germinated Ebony Seed')
	event.create('germinated_ivory_seed').displayName('Germinated Ivory Seed')
	event.create('geode_processing').displayName("Incomplete Geode")
	event.create('graw_tooth').displayName('Graw Tooth')
	event.create('gravitational_collapse_initiator').displayName('Gravitational Collapse Initiator')
	event.create('guardians_tablet').displayName('Guardian\'s Tablet')
	event.create('gusty_essence').displayName('Gusty Essence')
	event.create('heated_copper_ingot').displayName("Heated Copper Ingot")
	event.create('heavenly_aluminosilicate_catalyst').displayName('Heavenly Aluminosilicate Catalyst')
	event.create('helium_3_sifter_access_card').displayName('Helium-3 Sifting Unit Access Card')
	event.create('helium_3_sifting_unit').displayName('Helium-3 Sifting Unit')
	event.create('helium3_rover').displayName('Helium-3 Rover')
	event.create('hypercompressed_core').displayName('Hypercompressed Core')
	event.create('illusionary_amethyst').displayName('Illusionary Amethyst')
	event.create('illusionary_leather').displayName('Illusionary Leather')
	event.create('ilmenite_carbon_mixture').displayName('Ilmenite Carbon Mixture')
	event.create('ilmenite_dust').displayName('Ilmenite Dust')
	event.create('ilmenite_excavation_unit_access_card').displayName('Ilmenite Excavation Unit Access Card')
	event.create('ilmenite_excavation_unit').displayName('Ilmenite Excavation Unit')
	event.create('impure_aquamarine').displayName('Impure Aquamarine')
	event.create('impure_forged_shard').displayName('Impure Forged Shard')
	event.create('impure_slate').displayName('Impure Slate')
	event.create('impure_titanium_dust').displayName('Impure Titanium Dust')
	event.create('incomplete_combustion_chamber').displayName('Incomplete Combustion Chamber')
	event.create('psion_distillation_chamber_wall_processing').displayName('Incomplete Psion Distillation Chamber Wall')
	event.create('incomplete_creative_blaze_cake').displayName('Incomplete Creative Blaze Cake')
	event.create('infusion_token').displayName('Infusion Token')
	event.create('infusion_powder').displayName('Infusion Powder')
	event.create('insulated_plate_processing').displayName("Incomplete Insulated Plate")
	event.create('interference_essence').displayName('Interference Essence')
	event.create('iodine').displayName('Iodine')
	event.create('irilume_crystal').displayName('Irilume Crystal')
	event.create('iro_scrap').displayName('Iro Scrap')
	event.create('iron_oxide').displayName('Iron Oxide')
	event.create('ketone_catalyst').displayName('Ketone Catalyst')
	event.create('kingcap').displayName('Kingcap')
	event.create('kror_spike').displayName('Kror Spike')
	event.create('leadii_oxide').displayName('Lead(II) Oxide')
	event.create('limestone_dust').displayName("Limestone Dust")
	event.create('magical_bullet_slot').displayName('Magical Bullet Slot')
	event.create('mechbot_core').displayName('Mechbot Core')
	event.create('mithril_ingot').displayName('Mithril Ingot')
	event.create('neodymium_dust').displayName('Neodymium Dust')
	event.create('optic_nerve').displayName('Optic Nerve')
	event.create('overpowered_kit').displayName('Overpowered Kit')
	event.create('part_die').displayName('Part Die').tag('thermal:crafting/dies')
	event.create('pitchblende').displayName('Pitchblende')
	event.create('pip').displayName('Pip')
	event.create('pip_stack').displayName('Pip Stack')
	event.create('planar_stabilizer_processing').displayName('Incomplete Planar Stabilizer')
	event.create('platinum_catalyst').displayName('Platinum Catalyst')
	event.create('platinum_ingot').displayName("Platinum Ingot")
	event.create('platinum_gear').displayName('Platinum Gear')
	event.create('primordial_pearl').displayName('Primordial Pearl')
	event.create('pristine_gold_ingot').displayName('Pristine Gold Ingot')
	event.create('quantum_integral_components').displayName('Quantum Integral Components')
	event.create('quicklime_dust').displayName('Quicklime Dust')
	event.create('radiant_alloy').displayName('Radiant Alloy').glow(true)
	event.create('radiation_resistant_plate').displayName('Radiation Resistant Plate')
	event.create('rare_earth_excavation_unit_access_card').displayName('Rare Earth Excavation Unit Access Card')
	event.create('rare_earth_excavation_unit').displayName('Rare Earth Excavation Unit')
	event.create('raw_ebony_seed').displayName('Raw Ebony Seed')
	event.create('raw_ivory_seed').displayName('Raw Ivory Seed')
	event.create('red_mud').displayName('Red Mud')
	event.create('red_phosphorus').displayName('Red Phosphorus')
	event.create('refractory_mixture').displayName('Refractory Mixture')
	event.create('reinforced_ingot').displayName('Reinforced Ingot')
	event.create('rune_0').displayName('Rune ᛝ').glow(true)
	event.create('rune_1').displayName('Rune ᛇ').glow(true)
	event.create('rune_2').displayName('Rune ᛨ').glow(true)
	event.create('rune_3').displayName('Rune ᚹ').glow(true)
	event.create('rune_4').displayName('Rune ᚬ').glow(true)
	event.create('rune_5').displayName('Rune ᛄ').glow(true)
	event.create('rune_6').displayName('Rune ᛡ').glow(true)
	event.create('rune_7').displayName('Rune ᚳ').glow(true)
	event.create('rune_8').displayName('Rune ᛥ').glow(true)
	event.create('rune_9').displayName('Rune ᛕ').glow(true)
	event.create('rune_10').displayName('Rune ᛪ').glow(true)
	event.create('rune_11').displayName('Rune ᛯ').glow(true)
	event.create('rune_amalgam').displayName('Rune Amalgam').glow(true)
	event.create('seasonal_blank_rune').displayName('Seasonal Blank Rune')
	event.create('shadowlord_eye').displayName('Shadowlord Eye')
	event.create('shard_of_heroism').displayName('Shard of Heroism')
	event.create('shibuichi_ingot').displayName('Shibuichi Ingot')
	event.create('shifting_stone').displayName('Shifting Stone')
	event.create('silicon_carbide_powder').displayName('Silicon Carbide Powder')
	event.create('sinful_blank_rune').displayName('Sinful Blank Rune')
	event.create('sodium_bicarbonate').displayName('Sodium Bicarbonate')
	event.create('sodium_chromate').displayName('Sodium Chromate')
	event.create('sodium_dichromate').displayName('Sodium Dichromate')
	event.create('solder_ingot').displayName('Solder Ingot')
	event.create('steel_casing_materials').displayName('Steel Casing Materials')
	event.create('steel_sand').displayName("Steel Sand")
	event.create('stellar_alloy').displayName('Stellar Alloy Ingot')
	event.create('stellar_blueprint').displayName('Stellar Blueprint')
	event.create('stellar_circuit').displayName('Stellar Circuit')
	event.create('stellar_circuit_chemical_tank').displayName('Stellar Circuit (Creative Chemical Tank)')
	event.create('stellar_circuit_fluid_tank').displayName('Stellar Circuit (Creative Fluid Tank)')
	event.create('stellar_circuit_me').displayName('Stellar Circuit (Creative ME Storage Cell)')
	event.create('stellar_circuit_probe').displayName('Stellar Circuit (Creative Probe)')
	event.create('stellar_circuit_vending').displayName('Stellar Circuit (Creative Vending Upgrade)')
	event.create('stellar_circuit_worldshaper').displayName('Stellar Circuit (Creative Worldshaper)')
	event.create('stellar_core').displayName('Stellar Core')
	event.create('stibnite_dust').displayName('Stibnite Dust')
	event.create('storage_essence').displayName('Storage Essence')
	event.create('structure_frame_processing').displayName("Incomplete Structure Beam")
	event.create('suedohfedreen').displayName('Suedohfedreen')
	event.create('superconducting_bar').displayName("Superconductive Bar")
	event.create('superconducting_layer').displayName("Superconductive Layer")
	event.create('superconducting_sheet').displayName("Superconductive Sheet")
	event.create('superconducting_slab').displayName("Superconductive Slab")
	event.create('superconducting_blend').displayName("Superconductive Blend")
	event.create('superconducting_integral_components').displayName('Superconductive Integral Components')
	event.create('tanzanite').displayName('Tanzanite')
	event.create('tesseract').displayName('Tesseract')
	event.create('titanium_dust').displayName('Titanium Dust')
	event.create('titanium_salt').displayName('Titanium Salt')
	event.create('titanium_tetraiodide').displayName('Titanium Tetraiodide')
	event.create('tungsten_ingot').displayName('Tungsten Ingot')
	event.create('tyrosaur_horn').displayName("Tyrosaur Horn")
	event.create('ultimate_cotton_candy').displayName('Ultimate Cotton Candy')
	event.create('ultimate_control_circuit_materials').displayName('Ultimate Control Circuit Materials')
	event.create('ultimate_singularity_singularity').displayName('Ultimate Singularity Singularity').tooltip('You REALLY shouldn\'t be able to carry this...')
	event.create('vinocorne_petal').displayName('Vinocorne Petal')
	event.create('void_essence').displayName('Void Essence')
	event.create('wakurium_coil').displayName('Wakurium Coil')
	event.create('wet_essence').displayName('Wet Essence')
	event.create('white_phosphorus').displayName('White Phosphorus')
	event.create('white_plate').displayName('White Plate')
	event.create('white_substance').displayName('White Substance')
	event.create('xenate_salt').displayName('Xenate Salt')
	event.create('xenon_hexafluoride').displayName('Xenon Hexafluoride')
	event.create('xxeus_crown').displayName('Xxeus Crown')
    event.create('iridium_excavation_unit').displayName('Iridium Excavation Unit')
    event.create('iridium_excavation_unit_access_card').displayName('Iridium Excavation Unit Access Card')
    event.create('polyvinyl_chloride_powder').displayName('Polyvinyl Chloride Powder')
    event.create('phthalic_anhydride').displayName('Phthalic Anhydride')
    event.create('naphthalene').displayName('Naphthalene')
    event.create('graphene_sheet').displayName('Graphene Sheet')
    event.create('polyvinyl_chloride').displayName('Polyvinyl Chloride')
    event.create('platinum_plate').displayName('Platinum Plate')
	event.create('chilly_core').displayName('Chilly Core')

	event.create('bone_horn_processing').displayName('Incomplete Bone Horn')
	event.create('explosive_gems_processing').displayName('Incomplete Explosive Gems')
	event.create('boulder_dash_processing').displayName('Incomplete Boulder Dash')
	event.create('warlock_gem_processing').displayName('Incomplete Warlock Gem')
	event.create('book_of_shadows_processing').displayName('Incomplete Book of Shadows')
	event.create('yellow_spores_processing').displayName('Incomplete Yellow Spores')
	event.create('treat_bag_processing').displayName('Incomplete Treat Bag')
	event.create('shroom_stone_processing').displayName('Incomplete Shroom Stone')
	event.create('heavy_boulder_processing').displayName('Incomplete Heavy Boulder')
	event.create('darkly_powder_processing').displayName('Incomplete Darkly Powder')

	event.create('rune_air').displayName('Rune of Air')
	event.create('rune_autumn').displayName('Rune of Autumn')
	event.create('rune_earth').displayName('Rune of Earth')
	event.create('rune_envy').displayName('Rune of Envy')
	event.create('rune_fire').displayName('Rune of Fire')
	event.create('rune_gluttony').displayName('Rune of Gluttony')
	event.create('rune_greed').displayName('Rune of Greed')
	event.create('rune_lust').displayName('Rune of Lust')
	event.create('rune_mana').displayName('Rune of Mana')
	event.create('rune_pride').displayName('Rune of Pride')
	event.create('rune_sloth').displayName('Rune of Sloth')
	event.create('rune_spring').displayName('Rune of Spring')
	event.create('rune_summer').displayName('Rune of Summer')
	event.create('rune_water').displayName('Rune of Water')
	event.create('rune_winter').displayName('Rune of Winter')
	event.create('rune_wrath').displayName('Rune of Wrath')

	event.create('concept_of_capacity').displayName('Concept of Capacity')
	event.create('concept_of_continuity').displayName('Concept of Continuity')
	event.create('concept_of_dimension').displayName('Concept of Dimension')
	event.create('concept_of_energy').displayName('Concept of Energy')
	event.create('concept_of_fabrication').displayName('Concept of Fabrication')
	event.create('concept_of_fluid').displayName('Concept of Fluid')
	event.create('concept_of_infusion').displayName('Concept of Infusion')
	event.create('concept_of_material').displayName('Concept of Material')
	event.create('concept_of_space').displayName('Concept of Space')
	event.create('concept_of_specificity').displayName('Concept of Specificity')
	event.create('concept_of_frigidity').displayName('Concept of Frigidity')
	event.create('concept_of_the_stars').displayName('Concept of the Stars')
	event.create('concept_of_time').displayName('Concept of Time')

    event.create('refined_storage_essence').displayName('Essence of Laziness')
})

onEvent('block.registry', event => {
	
	event.create('steel_plated_ceramic_block').material('stone').hardness(3.0).resistance(5.0).requiresTool(true).tag('minecraft:mineable/pickaxe').tag('minecraft:needs_iron_tool').displayName('Steel-Plated Ceramic Block')
	event.create('cryolite_ore').material('stone').hardness(2.0).requiresTool(true).tag('minecraft:mineable/pickaxe').tag('minecraft:needs_iron_tool').displayName('Cryolite Ore').tag('forge:ores')
	event.create('fiberglass').material('wool').hardness(4.0).requiresTool(true).tag('minecraft:mineable/pickaxe').tag('minecraft:needs_stone_tool').displayName('Fiberglass')
	event.create('reinforced_casing').material('iron').hardness(5.0).requiresTool(true).tag('minecraft:mineable/pickaxe').tag('minecraft:needs_diamond_tool').displayName('Reinforced Casing')
	event.create('ceramic_block').material('stone').hardness(2.0).requiresTool(true).tag('minecraft:mineable/pickaxe').tag('minecraft:needs_stone_tool').displayName('Ceramic Block')
	event.create('aestanite_ore').material('stone').hardness(2.0).requiresTool(true).tag('minecraft:mineable/pickaxe').tag('minecraft:needs_diamond_tool').displayName('Aestanite Ore').tag('forge:ores')
	event.create('azure_block').material('glass').hardness(2.0).displayName('Azure Block')
	event.create('compressed_conjured_glass').material('glass').hardness(2.0).defaultCutout().opaque(false).fullBlock(false).displayName('Compressed Conjured Glass')
	event.create('conjured_glass').material('glass').hardness(2.0).defaultCutout().opaque(false).fullBlock(false).displayName('Conjured Glass')
	event.create('conjured_obsidian').material('stone').hardness(2.0).requiresTool(true).displayName('Conjured Obsidian')
	event.create('cracked_enhanced_block').material('iron').hardness(2.0).requiresTool(true).tag('minecraft:mineable/pickaxe').displayName('Cracked Enhanced Block')
	event.create('enhanced_block').material('iron').hardness(2.0).requiresTool(true).displayName('Enhanced Block')
	event.create('infused_end_stone').material('stone').hardness(2.0).requiresTool(true).displayName('Infused End Stone')
	event.create('otherworldly_planks').material('wood').hardness(2.0).requiresTool(true).displayName('Otherworldly Planks')
	event.create('pristine_gold_block').material('iron').hardness(2.0).requiresTool(true).displayName('Pristine Gold Block')
	event.create('starglass').material('glass').hardness(2.0).defaultCutout().opaque(false).fullBlock(false).displayName('Starglass')
	event.create('tanzanite_ore').material('stone').hardness(2.0).requiresTool(true).tag('minecraft:mineable/pickaxe').tag('minecraft:needs_iron_tool').displayName('Tanzanite Ore').tag('forge:ores')
	event.create('vitreous_block').material('iron').hardness(2.0).requiresTool(true).displayName('Vitreous Block')
	event.create('stellar_block_1').material('iron').hardness(2.0).requiresTool(true).displayName('Stellar Block')
	event.create('stellar_block_2').material('iron').hardness(2.0).requiresTool(true).displayName('Stellar Block')
	event.create('stellar_block_3').material('iron').hardness(2.0).requiresTool(true).displayName('Stellar Block')
	event.create('stellar_block_4').material('iron').hardness(2.0).requiresTool(true).displayName('Stellar Block')
	event.create('dark_matter_frame').material('iron').hardness(2.0).requiresTool(true).displayName('Dark Matter Frame')
	event.create('draconic_frame').material('iron').hardness(2.0).requiresTool(true).displayName('Draconic Frame')
	event.create('infused_ore').material('stone').hardness(2.0).requiresTool(true).displayName('Infused Ore').tag('forge:ores')
	event.create('irilume').material('iron').hardness(2.0).requiresTool(true).displayName('Irilume')
	event.create('pitchblende_ore').material('stone').hardness(2.0).requiresTool(true).displayName('Pitchblende Ore').tag('forge:ores')
	event.create('plutonium_block').material('iron').hardness(2.0).requiresTool(true).displayName('Plutonium Block')
	event.create('quantanium_casing').material('iron').hardness(2.0).requiresTool(true).displayName('Quantanium Casing')
	event.create('time_infused_casing').material('iron').hardness(2.0).requiresTool(true).displayName('Time-Infused Casing')
	event.create('tanzanite_block').material('iron').hardness(2.0).requiresTool(true).displayName('Tanzanite Block')
	event.create('unrefined_awakened_draconium').material('iron').hardness(2.0).requiresTool(true).displayName('Unrefined Awakened Draconium')
	event.create('actively_cooled_casing').material('iron').hardness(2.0).requiresTool(true).displayName('Actively Cooled Casing')
	event.create('alumina_refractory_bricks').material('stone').hardness(2.0).requiresTool(true).displayName('Alumina Refractory Bricks')
	event.create('ilmenite_ore').material('stone').hardness(2.0).requiresTool(true).displayName('Ilmenite Ore').tag('forge:ores')
	event.create('hop_graphite_block').material('iron').hardness(2.0).requiresTool(true).displayName('HOP Graphite Block')
	event.create('superconductive_block').material('iron').hardness(2.0).requiresTool(true).displayName('Superconductive Block')
	event.create('annealed_copper_block').material('iron').hardness(2.0).requiresTool(true).displayName('Annealed Copper Block')
	event.create('molybdenum_block').material('iron').hardness(2.0).requiresTool(true).displayName('Molybdenum Block')
	event.create('tungsten_block').material('iron').hardness(2.0).requiresTool(true).displayName('Tungsten Block')
	event.create('test_block').material('iron').hardness(17.0).requiresTool(true).displayName('Test Block')
	event.create('tungsten_ore').material('stone').hardness(2.0).requiresTool(true).displayName('Tungsten Ore').tag('forge:ores')
	event.create('platinum_ore').material('stone').hardness(2.0).requiresTool(true).displayName('Platinum Ore').tag('forge:ores')
	event.create('aquamarine_block').material('iron').hardness(2.0).requiresTool(true).displayName('Aquamarine Block')
	event.create('dark_matter_alloy_block').material('iron').hardness(2.0).requiresTool(true).displayName('Dark Matter Alloy Block')
	event.create('corundum_ore').material('stone').hardness(2.0).requiresTool(true).displayName('Corundum Ore').tag('forge:ores')
	event.create('unempowered_ancient_rock').material('stone').hardness(2.0).requiresTool(true).displayName('Unempowered Ancient Rock')
    event.create('radiation_resistant_casing').material('iron').hardness(3).requiresTool(true).displayName('Radiation Resistant Casing')

})

onEvent('fluid.registry', event => {

	event.create('magma_gelatin')
	  .textureThick(0xA32A11)
	  .displayName('Magma Gelatin')
				   
	event.create('pristine_solution')
	  .textureThin(0x96E8DA)
	  .displayName('Pristine Solution')

	event.create('volatile_golden_mixture')
	  .textureThick(0xFFFF00)
	  .displayName('Volatile Golden Mixture')

	event.create('nitro_diesel')
	  .textureThin(0xBAEB24)
	  .displayName('Nitro-Diesel')

	event.create('liquid_carbon_dioxide')
	  .textureThin(0x2ED184)
	  .displayName('Carbon Dioxide')

	event.create('molten_superconductive')
	  .textureThick(0xC8CCBD)
	  .displayName('Molten Superconductive')

	event.create('molten_stainless_steel')
	  .textureThick(0xDDDDDD)
	  .displayName('Molten Stainless Steel')

	event.create('molten_chromium')
	  .textureThick(0xF7F6E1)
	  .displayName('Molten Chromium')

	event.create('liquid_nitrogen')
	  .textureThin(0x1B77E8)
	  .displayName('Nitrogen')

	event.create('liquid_ammonia')
	  .textureThin(0x1669CE)
	  .displayName('Ammonia')

	event.create('liquid_methanol')
	  .textureThin(0xD69CD0)
	  .displayName('Methanol')

	event.create('meathilamyn')
	  .textureThin(0xEFBAE9)
	  .displayName('Meathilamyn')

	event.create('phenylacetic_acid')
	  .textureThin(0xEBEFBA)
	  .displayName('Phenylacetic Acid')

	event.create('phenylacetone')
	  .textureThin(0xD6D6CD)
	  .displayName('Phenylacetone')

	event.create('acetic_anhydride')
	  .textureThin(0xD6D1C7)
	  .displayName('Acetic Anhydride')

	event.create('blue_liquid')
	  .textureThin(0x3030FF)
	  .displayName('Blue Liquid')

	event.create('white_liquid')
	  .textureThin(0xFFFFFF)
	  .displayName('White Liquid')

	event.create('distilled_water')
	  .textureThin(0x229FBF)
	  .displayName('Distilled Water')
	
	event.create('very_heavy_water')
	  .textureThin(0x18167C)
	  .displayName('Very Heavy Water')

	event.create('fluoroantimonic_acid')
	  .textureThin(0x695899)
	  .displayName('Fluoroantimonic Acid')

	event.create('molten_antimony_oxide')
	  .textureThick(0xC3CCD8)
	  .displayName('Molten Antimony Oxide')
	  
	event.create('molten_antimony_trichloride')
	  .textureThick(0xC3D8C9)
	  .displayName('Molten Antimony Trichloride')
	  
	event.create('antimony_pentachloride')
	  .textureThin(0xBADBC3)
	  .displayName('Antimony Pentachloride')

	event.create('antimony_pentafluoride')
	  .textureThin(0xD5DBBA)
	  .displayName('Antimony Pentafluoride')

	event.create('acidic_awakened_draconium_solution')
	  .textureThin(0xED9F38)
	  .displayName('Acidic Awakened Draconium Solution')

	event.create('awakened_draconium_solution')
	  .textureThin(0xEF951F)
	  .displayName('Awakened Draconium Solution')

	event.create('concentrated_awakened_draconium_solution')
	  .textureThin(0xF98E02)
	  .displayName('Concentrated Awakened Draconium Solution')

	event.create('molten_fiberglass')
	  .textureThick(0xDDDDBB)
	  .displayName('Molten Fiberglass')

	event.create('aluminate_solution')
	  .textureThick(0xF4D7E7)
	  .displayName('Aluminate Solution')

	event.create('liquid_air')
	  .textureThin(0xABC2CC)
	  .displayName('Liquid Air')

	event.create('liquid_argon')
	  .textureThin(0x9DDBA6)
	  .displayName('Argon')

	event.create('silicon_carbide_paste')
	  .textureThick(0x80A385)
	  .displayName('Silicon Carbide Paste')

	event.create('void')
	  .textureThin(0x000000)
	  .displayName('void')

	event.create('cold_water')
	  .textureThin(0x445EE2)
	  .displayName('Cold Water')

	event.create('molten_cryolite')
	  .textureThick(0xE2E2AC)
	  .displayName('Molten Cryolite')

	event.create('liquid_sodium_hydroxide')
	  .textureThin(0xF2F2EA)
	  .displayName('Liquid Sodium Hydroxide')

	event.create('cryogenic_oxygen')
	  .textureThin(0x5CA8CE)
	  .displayName('Cryogenic Liquid Oxygen')

	event.create('cryogenic_nitrogen')
	  .textureThin(0x1B55D3)
	  .displayName('Cryogenic Liquid Nitrogen')

	event.create('cryogenic_argon')
	  .textureThin(0x8CCCA3)
	  .displayName('Cryogenic Liquid Argon')

	event.create('cryogenic_xenon')
	  .textureThin(0x70CCCA)
	  .displayName('Cryogenic Liquid Xenon')

	event.create('iodane')
	  .textureThin(0x6249D1)
	  .displayName('Iodane')

	event.create('molten_ilmenite_carbon')
	  .textureThick(0x594D42)
	  .displayName('Molten Ilmenite-Carbon')

	event.create('titanium_tetrachloride')
	  .textureThick(0xC9AE2A)
	  .displayName('Titanium Tetrachloride')

	event.create('liquid_xenon')
	  .textureThin(0x2AC9A9)
	  .displayName('Xenon')

	event.create('molten_dioxygen_difluoride')
	  .textureThick(0x6D0F15)
	  .displayName('Molten Dioxygen Difluoride')

	event.create('hydrofluoric_acid')
	  .textureThin(0xAAAA9B)
	  .displayName('Hydrofluoric Acid')

	event.create('hydrochloric_acid')
	  .textureThin(0x8FADA7)
	  .displayName('Hydrochloric Acid')

	event.create('xenic_acid')
	  .textureThin(0x8CE2D1)
	  .displayName('Xenic Acid')

	event.create('liquid_inert_air')
	  .textureThin(0x9678B6)
	  .displayName('Liquid Inert Xenon-Enriched Air')

	event.create('hot_heavy_water')
	  .textureThin(0x161E72)
	  .displayName('Hot Heavy Water')

	event.create('bauxite_slurry')
	  .textureThin(0x634220)
	  .displayName('Bauxite Slurry')

	event.create('heated_bauxite_slurry')
	  .textureThin(0x592B1D)
	  .displayName('Heated Bauxite Slurry')

	event.create('nitric_oxide')
	  .textureThin(0xDCE4E5)
	  .displayName('Nitric Oxide')

	event.create('liquid_nitrogen_dioxide')
	  .textureThin(0xDDAE96)
	  .displayName('Nitrogen Dioxide')

	event.create('nitric_acid')
	  .textureThin(0xEDEA5E)
	  .displayName('Nitric Acid')

	event.create('natural_gas')
	  .textureThin(0xF2F2EF)
	  .displayName('Natural Gas')

	event.create('cracked_natural_gas')
	  .textureThin(0xC6C6C6)
	  .displayName('Cracked Natural Gas')

	event.create('xenon_difluoride')
	  .textureThin(0xABCDE7)
	  .displayName('Xenon Difluoride')

	event.create('ammonium_nitrate_solution')
	  .textureThin(0xC2C4C3)
	  .displayName('Ammonium Nitrate Solution')
    
    event.create('vinyl_chloride')
      .textureThin(0xCDD6d5)
      .displayName('Vinyl Chloride')
    
    event.create('diisobutyl_phthalate')
      .textureThin(0xDFEBED)
      .displayName('Diisobutyl Phthalate')

    event.create('isobutanol')
      .textureThin(0xF5F5EB)
      .displayName('Isobutanol')

    event.create('carbon_monoxide')
      .textureThin(0xB0CFCF)
      .displayName('Carbon Monoxide')

    event.create('propylene')
      .textureThin(0xF4F7BC)
      .displayName('Propylene')
/*
    GASES.register('essence_of_canredback_being_wrong',0xFAFAFA)
*/
})

GASES.register('carbon_dioxide', 0x2ED184)
GASES.register('copper_sulfide', 0xD1922E)
GASES.register('nitrogen', 0x1B77E8)
GASES.register('ammonia', 0x1669CE)
GASES.register('ethanol', 0xD2C7D8)
GASES.register('methanol', 0xD69CD0)
GASES.register('very_heavy_water_vapor', 0x62668C)
GASES.register('acidic_awakened_draconium_solution', 0xED9F38)
GASES.register('ammonium_chloride', 0xEADCF2)
GASES.register('hydroxide', 0xF4D7E7)
GASES.register('impure_helium_3', 0x7ECC87)
GASES.register('air', 0xABC2CC)
GASES.register('sodium_hydroxide', 0xF2F2EA)
GASES.register('hydrazine', 0xF45D55)
GASES.register('hydrogen_iodide', 0x6142ED)
GASES.register('xenon_trioxide', 0x652FD8)
GASES.register('inert_air', 0x9678B6)
GASES.register('low_enriched_uranium_fuel', 0x010A00)
GASES.register('low_enriched_nuclear_waste', 0x606B5E)
GASES.register('nitrogen_dioxide', 0xDDAE96)
GASES.register('hydrogen_peroxide', 0xBADFFF)
GASES.register('ender_air', 0x425B5E)


GASES.register($EventBuses.getModEventBus('kubejs').get())
